import Layout from "@/components/Layout"
import Head from "next/head"
import Image from "next/image"
import profilPic from "../../public/images/profile/Photo_Prof1-modif2.png"
import bg from "../../public/images/header_bg.jpeg"
import AnimatedText from "../components/AnimatedText"
import Link from "next/link"
import { DownIcon } from "@/components/Icons"
import HireMe from "@/components/HireMe"



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className="flex items-center text-dark w-full" style={{
        backgroundImage: `linear-gradient(90deg, rgba(0, 0, 0, 0.6), rgba(20, 20, 20, 0.7)), url(${bg.src})`
      }}>
        <Layout className="bg-transparent  pb-0 " >

          <div className="flex items-center justify-between bg-transparent" >
            <div className="w-2/5 p-0 ">
              <Image src={profilPic} alt="photo" />
            </div>
            <div className="w-3/5 text-white">
              <AnimatedText text="Im Marwa BEN TAMANSOURT. Full Stack Web Developer" className="text-left text-white" />
              <p className="my-4 text-base font-medium">
                Passionate about new technologies, I had the opportunity
                to work as a full-stack Symfony developer for four years.
                Subsequently, I took on the role of project manager for one
                year. It was a great opportunity to lead a team of developers
                and have daily meetings with Francophone clients.
                After that, I worked as a freelance webmaster and community manager
                while continuing my masters studies.
              </p>
              <div className="flex items-center  mt-2  justify-start ">
                <Link href="/CV_BenTamansourt_Marwa.pdf" target={"_blank"}
                  className="mr-2 flex items-center bg-dark text-light p-2.5 px-4
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >Resum <DownIcon className={"w-6 ml-4 hover:stroke-dark"} /></Link>


                <Link href="mailto:marwa.bentamansourt@gmail.com" target={"_blank"}
                  className="flex items-center bg-light text-dark p-2.5 px-4
                rounded-lg text-lg font-semibold hover:bg-dark hover:text-light
                border-2 border-solid border-dark hover:border-transparent"
                >Contact</Link>
              </div>
            </div>
          </div>

        </Layout>
        <HireMe />
      </main>
    </>
  )
}
